include: package:effective_dart/analysis_options.yaml

linter:
    rules:
      public_member_api_docs: false
      prefer_relative_imports: false
      avoid_classes_with_only_static_members: false
      lines_longer_than_80_chars: false
      avoid_relative_lib_imports: false