name: projectbasesnow
description: A new Flutter package that is used to base all flutter projects of snowmanlabs.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  catcher: ^0.3.6
  animations: ^1.0.0+5
  device_info: ^0.4.2+3
  intl: ^0.16.1
  dio_interceptors: ^0.0.4+1
  dio_http_cache: ^0.2.6
  mobx_widget: ^0.4.0
  responsive_framework: ^0.0.5
  i18n_extension: ^1.3.5
  flutter_platform_widgets: ^0.32.5
  device_preview: ^0.4.4
  google_fonts: ^1.0.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter

flutter: